POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "joonas",
    "name": "Joonas Kinnunen",
    "phone": "0402210499",
    "email": "joonas.kinn@gmail.com",
    "password": "salasana"
}